# Generated by Django 2.0.6 on 2018-06-17 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adtitle', models.CharField(max_length=253)),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('house_type', models.CharField(choices=[('APPARTMENTS', 'APPARTMENTS'), ('STUDIO', 'STUDIO'), ('CABIN', 'CABIN'), ('BUNGALOW', 'BUNGALOW'), ('EARTHHOUSE', 'EARTHHOUSE')], max_length=50)),
                ('no_beds', models.IntegerField()),
                ('no_bedrooms', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
