# Generated by Django 2.0.6 on 2018-06-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20180618_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='slug',
            field=models.CharField(blank=True, max_length=253, unique=True),
        ),
    ]
