# Generated by Django 2.0.6 on 2018-06-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_house_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField(default=False)),
                ('essential', models.BooleanField(default=False)),
                ('shampoo', models.BooleanField(default=False)),
                ('closet', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('smoke_detector', models.BooleanField(default=False)),
                ('first_aid', models.BooleanField(default=False)),
                ('fire_extinguisher', models.BooleanField(default=False)),
            ],
        ),
    ]
