# Generated by Django 2.0.6 on 2018-06-21 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='amenities_type',
            field=models.CharField(default='essential', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amenities',
            name='mod_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='amenities',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
