# Generated by Django 2.0.6 on 2018-06-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_auto_20180621_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='closet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='essential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='fire_extinguisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='first_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='shampoo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='smoke_detector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
    ]
