# Generated by Django 2.0.6 on 2018-06-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_auto_20180625_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='pool',
            field=models.BooleanField(default=False),
        ),
    ]
