# Generated by Django 2.0.6 on 2018-07-02 20:53

from django.db import migrations, models
import house.models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_houseimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseimages',
            name='house',
        ),
        migrations.AddField(
            model_name='house',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=house.models.upload_location),
        ),
        migrations.DeleteModel(
            name='HouseImages',
        ),
    ]
