# Generated by Django 2.0.6 on 2018-07-29 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0015_auto_20180702_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_guests', models.SmallIntegerField(default=0)),
                ('nights', models.SmallIntegerField(blank=True, default=0)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('extra_info', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_notification_date', models.DateTimeField(blank=True, null=True)),
                ('payment_confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='house.House')),
            ],
        ),
    ]
