# Generated by Django 2.0.6 on 2018-07-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0017_auto_20180729_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
